const String githubResult = '''{
  "total_count": 5,
  "incomplete_results": false,
  "items": [
    {
      "login": "moisesmartins",
      "id": 30622686,
      "node_id": "MDQ6VXNlcjMwNjIyNjg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/30622686?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/moisesmartins",
      "html_url": "https://github.com/moisesmartins",
      "followers_url": "https://api.github.com/users/moisesmartins/followers",
      "following_url": "https://api.github.com/users/moisesmartins/following{/other_user}",
      "gists_url": "https://api.github.com/users/moisesmartins/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/moisesmartins/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/moisesmartins/subscriptions",
      "organizations_url": "https://api.github.com/users/moisesmartins/orgs",
      "repos_url": "https://api.github.com/users/moisesmartins/repos",
      "events_url": "https://api.github.com/users/moisesmartins/events{/privacy}",
      "received_events_url": "https://api.github.com/users/moisesmartins/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "moisesmartins14-zz",
      "id": 29459515,
      "node_id": "MDQ6VXNlcjI5NDU5NTE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/29459515?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/moisesmartins14-zz",
      "html_url": "https://github.com/moisesmartins14-zz",
      "followers_url": "https://api.github.com/users/moisesmartins14-zz/followers",
      "following_url": "https://api.github.com/users/moisesmartins14-zz/following{/other_user}",
      "gists_url": "https://api.github.com/users/moisesmartins14-zz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/moisesmartins14-zz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/moisesmartins14-zz/subscriptions",
      "organizations_url": "https://api.github.com/users/moisesmartins14-zz/orgs",
      "repos_url": "https://api.github.com/users/moisesmartins14-zz/repos",
      "events_url": "https://api.github.com/users/moisesmartins14-zz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/moisesmartins14-zz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "moisesmartins-dev",
      "id": 90873584,
      "node_id": "MDQ6VXNlcjkwODczNTg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/90873584?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/moisesmartins-dev",
      "html_url": "https://github.com/moisesmartins-dev",
      "followers_url": "https://api.github.com/users/moisesmartins-dev/followers",
      "following_url": "https://api.github.com/users/moisesmartins-dev/following{/other_user}",
      "gists_url": "https://api.github.com/users/moisesmartins-dev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/moisesmartins-dev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/moisesmartins-dev/subscriptions",
      "organizations_url": "https://api.github.com/users/moisesmartins-dev/orgs",
      "repos_url": "https://api.github.com/users/moisesmartins-dev/repos",
      "events_url": "https://api.github.com/users/moisesmartins-dev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/moisesmartins-dev/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MoisesMartins07",
      "id": 24777274,
      "node_id": "MDQ6VXNlcjI0Nzc3Mjc0",
      "avatar_url": "https://avatars.githubusercontent.com/u/24777274?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MoisesMartins07",
      "html_url": "https://github.com/MoisesMartins07",
      "followers_url": "https://api.github.com/users/MoisesMartins07/followers",
      "following_url": "https://api.github.com/users/MoisesMartins07/following{/other_user}",
      "gists_url": "https://api.github.com/users/MoisesMartins07/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MoisesMartins07/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MoisesMartins07/subscriptions",
      "organizations_url": "https://api.github.com/users/MoisesMartins07/orgs",
      "repos_url": "https://api.github.com/users/MoisesMartins07/repos",
      "events_url": "https://api.github.com/users/MoisesMartins07/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MoisesMartins07/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MoisesMartins1",
      "id": 49240846,
      "node_id": "MDQ6VXNlcjQ5MjQwODQ2",
      "avatar_url": "https://avatars.githubusercontent.com/u/49240846?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MoisesMartins1",
      "html_url": "https://github.com/MoisesMartins1",
      "followers_url": "https://api.github.com/users/MoisesMartins1/followers",
      "following_url": "https://api.github.com/users/MoisesMartins1/following{/other_user}",
      "gists_url": "https://api.github.com/users/MoisesMartins1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MoisesMartins1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MoisesMartins1/subscriptions",
      "organizations_url": "https://api.github.com/users/MoisesMartins1/orgs",
      "repos_url": "https://api.github.com/users/MoisesMartins1/repos",
      "events_url": "https://api.github.com/users/MoisesMartins1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MoisesMartins1/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}''';
